# -*- coding: utf-8 -*-
"""Data_Cleaning_Pratice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XsMNdUeVYbDayeskBONpv6ZR0GSb2bxJ
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/sample_data/messy_customer_sales_data.csv")

"""**Data Types**

---
"""

df.info()

df.describe().round()

df.isnull().sum()

df.shape

df[df.duplicated()]

df['Customer_ID'].value_counts().head()

df[df['Customer_ID']=='CUST10800']

"""**See unique value**

---
"""

for col in df.columns:
  if df[col].nunique()<20:
    print(df[col].value_counts())
    print('*'*50)

"""**Handling The Null Values**

---
"""

df.isnull().sum()

df['Age'].unique()

import re
def extract_age (age):
  age_num = re.findall('[0-9]+',str(age))
  if len(age_num)>0:
    return age_num[0]
  else:
    return age
df['Age']= df['Age'].apply (lambda x: extract_age(x))

df['Age'].unique()

df_age= df[df['Age']!='nan years']['Age']

age_median = int(df_age.dropna().astype('int64').median())

age_median

df.replace('nan years',age_median,inplace=True)

df['Age'].fillna(age_median,inplace=True)

df['Age'].unique()

df['Purchase_Amount'].fillna(df['Purchase_Amount'].median(),inplace = True)

for col in ['Gender','City','Country','Feedback_Score','Last_Purchase_Date']:
  df[col].fillna(df[col].mode()[0],inplace =True)

df.dropna(subset='Customer_ID',inplace=True)

df.isnull().sum()

"""**Fixed Inconsisstent Formatting**

---
"""

df['Gender'].unique()

df['Gender']=df['Gender'].str.lower().str.strip()

df['Gender'].replace({'m':'male','f':'female'},inplace=True)

df['Gender'].unique()

df['City']=df['City'].str.lower()

df['Country'].unique()

df['Country']=df['Country'].str.lower()

df['Country'].replace({'ind':'india'},inplace=True)

df['Country'].unique()

for col in df.columns:
  if df[col].nunique()<20:
    print(df[col].value_counts())
    print('--'*50)

"""**Handling Duplicates**

---

"""

df[df.duplicated()].shape

df.drop_duplicates(inplace=True)

df['Customer_ID'].value_counts().head()

df.drop_duplicates(subset=['Customer_ID'],keep='first',inplace=True)

"""**Correcting Data Types**

---
"""

df['Age']=df['Age'].astype('int64')

df['Signup_Date']=pd.to_datetime(df['Signup_Date'])

df['Last_Purchase_Date']=pd.to_datetime(df['Last_Purchase_Date'])

df.dtypes

